  CREATE TABLE "BANK_CUSTOMERS_BENEFICIARIES" 
   (	
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999 
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BENEFICIARIES_NAME" VARCHAR2(128), 
	"BENEFICIARIES_TO_CUSTID" NUMBER, 
	"BENEFICIARIES_FROM_CUSTID" NUMBER, 
	 CONSTRAINT "BANK_CUSTOMERS_BENEFICIARIES_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "BANK_CUSTOMERS_BENEFICIARIES" ADD CONSTRAINT "BANK_CUSTOMERS_BENEFICIARIES_ID_FK" 
      FOREIGN KEY ("BENEFICIARIES_FROM_CUSTID")
	  REFERENCES "BANK_CUSTOMERS" ("ID") ENABLE;

  CREATE INDEX "BANK_CUSTOMERS_BENEFICIARIES_I1" ON "BANK_CUSTOMERS_BENEFICIARIES" ("BENEFICIARIES_FROM_CUSTID") 
  ;

  --------
  2. Store applications in the **BANK\_CUSTOMERS** table, you can also create a table with different name such as bank application table or just applications table, it is your choice. please feel free to add or remove columns as per your application needs.  

    ```sql 
        <copy>
        CREATE TABLE "BANK_CUSTOMERS" 
        (	
            "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 999999999999 
            INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
            "GENDER" VARCHAR2(1) 
            USING INDEX  ENABLE
        ) ;
        </copy>
    ``` 
----------

  select * from BANK_CUSTOMERS_BENEFICIARIES 
  WHERE BENEFICIARIES_FROM_CUSTID = 
  (select ID from bank_customers where upper(email) = upper(v('APP_USER')) AND rownum = 1);
----------
    ```sql 
        <copy>
        select * from BANK_CUSTOMERS_BENEFICIARIES 
        WHERE BENEFICIARIES_FROM_CUSTID = 
        (select ID from bank_customers where upper(email) = upper(v('APP_USER')) AND rownum = 1);  
        </copy>
    ```

    ```sql 
        <copy>
        --login as ADMIN user 
        GRANT EXECUTE ON DBMS_AQADM TO DOCUSER;   
        GRANT EXECUTE ON DBMS_AQ TO DOCUSER;   
        GRANT AQ_ADMINISTRATOR_ROLE TO DOCUSER; 
        
        EXECUTE dbms_aqadm.grant_system_privilege('ENQUEUE_ANY','DOCUSER',FALSE);

        EXECUTE dbms_aqadm.grant_system_privilege('DEQUEUE_ANY','DOCUSER',FALSE); 
        </copy>
    ```

