prompt --application/pages/page_00094
begin
--   Manifest
--     PAGE: 00094
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>7477895910065199
,p_default_application_id=>114
,p_default_id_offset=>8992108442064454
,p_default_owner=>'DEMOUSER'
);
wwv_flow_imp_page.create_page(
 p_id=>94
,p_name=>'PostAccountCreate'
,p_alias=>'POSTACCOUNTCREATE'
,p_step_title=>'PostAccountCreate'
,p_autocomplete_on_off=>'OFF'
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.t-Header-branding { ',
'    display: none;  ',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_overwrite_navigation_list=>'Y'
,p_page_is_public_y_n=>'Y'
,p_protection_level=>'C'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(24342638923724906)
,p_plug_name=>'Public Home User'
,p_plug_display_sequence=>20
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" type="text/css" />',
'<link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" /> ',
'<link href="#APP_FILES#templates/replace-this/css/styles.css" rel="stylesheet" />',
'<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />',
'<link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />',
' ',
'<script src="#APP_FILES#oda/settings#MIN#.js"></script>',
'<script src="#APP_FILES#oda/web-sdk.js" onload="initSdk(''Bots'')"></script>',
'<link rel="stylesheet" href="#APP_FILES#oda/redwood-base-madhu.css" > ',
' ',
'<!-- ',
'<link rel="stylesheet" href="#APP_FILES#oda24/style/style.css">',
'<script src="#APP_FILES#oda24/scripts/settings.js" defer></script>',
'<script src="#APP_FILES#oda24/scripts/web-sdk#MIN#.js" onload="initSdk(''Bots'')" defer></script>',
'-->',
'',
'<!-- Navigation-->',
'        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">',
'            <div class="container px-4 px-lg-5">',
'                <a class="navbar-brand" href="#page-top" style="color:#4E4139">',
'                    <img src="#APP_FILES#icons/app-icon-512.png" width="48px" height="48px" alt="..." />  AI for Financial Services</a>',
'                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-t'
||'oggler-icon"></span></button>',
'                <div class="collapse navbar-collapse" id="navbarResponsive">',
'                    <ul class="navbar-nav ms-auto my-2 my-lg-0">',
'                        <!-- <li class="nav-item"><a class="nav-link" href="f?p=&APP_ID.:88:&SESSION.::&DEBUG.::::">My Profile</a></li>',
'                        <li class="nav-item"><a class="nav-link" href="f?p=&APP_ID.:58:&SESSION.::&DEBUG.::::">Open Bank Account</a></li>  ',
'                        <li class="nav-item"><a class="nav-link" href="&LOGOUT_URL.">Logout</a></li> -->',
'                    </ul>',
'                </div>',
'            </div>',
'        </nav>',
'        <!-- Masthead-->',
'        <header class="masthead" style="background: url(''#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/finservbuilding.jpg'');">',
'            <div class="container px-4 px-lg-5 h-100">',
'                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">',
'                    <div class="col-lg-8 align-self-end">',
'                         &nbsp;',
'                        <hr class="divider" />',
'                    </div>',
'                    <div class="col-lg-8 align-self-baseline">',
'                        <p class="text-white-75 mb-5">Proin sed bibendum dui. Maecenas at eros sed metus imperdiet gravida. Ut vehicula et orci in sollicitudin. Nulla hendrerit iaculis vulputate. Suspendisse ac magna pulvinar, pellentesque sem fringi'
||'lla,</p>',
'                        <a class="btn btn-primary btn-xl" href="f?p=&APP_ID.:9999:&SESSION.::&DEBUG.::::">Login & Update your profile </a>',
'                    </div>',
'                </div>',
'            </div>',
'        </header>',
'        <!-- About-->',
'        <section class="page-section bg-primary" id="about">',
'            <div class="container px-4 px-lg-5">',
'                <div class="row gx-4 gx-lg-5 justify-content-center">',
'                    <div class="col-lg-8 text-center">',
'                        <h2 class="text-white mt-0">We''ve got what you need!</h2>',
'                        <hr class="divider divider-light" />',
'                        <p class="text-white-75 mb-4">Dapibus sapien. Etiam non massa vitae ligula suscipit blandit sed vitae velit. Curabitur mattis massa ac nisl elementum, in egestas dolor iaculis. Cras aliquam sem ipsum, non mollis lectus tincidu'
||'nt et. Praesent mi neque, sollicitudin a nisl at, rhoncus suscipit tellus. Aenean at dapibus nunc</p>',
'                        <a class="btn btn-light btn-xl" href="f?p=&APP_ID.:9999:&SESSION.::&DEBUG.::::">Open Bank Account </a>',
'                    </div>',
'                </div>',
'            </div>',
'        </section>',
'        <!-- Services-->',
'        <section class="page-section" id="services">',
'            <div class="container px-4 px-lg-5">',
'                <h2 class="text-center mt-0">At Your Service</h2>',
'                <hr class="divider" />',
'                <div class="row gx-4 gx-lg-5">',
'                    <div class="col-lg-3 col-md-6 text-center">',
'                        <div class="mt-5">',
'                            <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>',
'                            <h3 class="h4 mb-2">Internet Banking</h3>',
'                            <p class="text-muted mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam!</p>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-3 col-md-6 text-center">',
'                        <div class="mt-5">',
'                            <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>',
'                            <h3 class="h4 mb-2">Best EMI Loans</h3>',
'                            <p class="text-muted mb-0">Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit pariatur.</p>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-3 col-md-6 text-center">',
'                        <div class="mt-5">',
'                            <div class="mb-2"><i class="bi-globe fs-1 text-primary"></i></div>',
'                            <h3 class="h4 mb-2">Mobile Banking</h3>',
'                            <p class="text-muted mb-0">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore!</p>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-3 col-md-6 text-center">',
'                        <div class="mt-5">',
'                            <div class="mb-2"><i class="bi-heart fs-1 text-primary"></i></div>',
'                            <h3 class="h4 mb-2">24*7 Support</h3>',
'                            <p class="text-muted mb-0">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni Duis aute irure dolor in reprehenderit</p>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'        </section>',
'        <!-- Portfolio-->',
'        <div id="portfolio">',
'            <div class="container-fluid p-0">',
'                <div class="row g-0">',
'                    <div class="col-lg-4 col-sm-6">',
'                        <a class="portfolio-box" href="#" title="Project Name">',
'                            <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/1a.jpg" alt="..." />',
'                            <div class="portfolio-box-caption">',
'                                <div class="project-category text-white-50">Core Banking</div>',
'                                <div class="project-name">Internet Banking</div>',
'                            </div>',
'                        </a>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6">',
'                        <a class="portfolio-box" href="#" title="Project Name">',
'                            <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/2a.jpg" alt="..." />',
'                            <div class="portfolio-box-caption">',
'                                <div class="project-category text-white-50">Core Banking</div>',
'                                <div class="project-name">Mobile Banking</div>',
'                            </div>',
'                        </a>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6">',
'                        <a class="portfolio-box" href="#" title="Project Name">',
'                            <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/3a.jpg" alt="..." />',
'                            <div class="portfolio-box-caption">',
'                                <div class="project-category text-white-50">Premium Cards</div>',
'                                <div class="project-name">Gold Credit Cards</div>',
'                            </div>',
'                        </a>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6">',
'                        <a class="portfolio-box" href="#" title="Project Name">',
'                            <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/4a.jpg" alt="..." />',
'                            <div class="portfolio-box-caption">',
'                                <div class="project-category text-white-50">Support</div>',
'                                <div class="project-name">24*7 Customer Support</div>',
'                            </div>',
'                        </a>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6">',
'                        <a class="portfolio-box" href="#" title="Project Name">',
'                            <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/5a.jpg" alt="..." />',
'                            <div class="portfolio-box-caption">',
'                                <div class="project-category text-white-50">Realtime Data</div>',
'                                <div class="project-name">Access your data anytime</div>',
'                            </div>',
'                        </a>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6">',
'                        <a class="portfolio-box" href="#" title="Project Name">',
'                            <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/6a.jpg" alt="..." />',
'                            <div class="portfolio-box-caption p-3">',
'                                <div class="project-category text-white-50">Secure</div>',
'                                <div class="project-name">Highly Secure Banking</div>',
'                            </div>',
'                        </a>',
'                    </div>',
'                </div>',
'            </div>',
'        </div>',
'        <!-- Call to action-->',
'        <section class="page-section bg-dark text-white">',
'            <div class="container px-4 px-lg-5 text-center">',
'                <h2 class="mb-4">Explore our Internet Banking!</h2>',
'                <a class="btn btn-light btn-xl" href="f?p=&APP_ID.:48:&SESSION.::&DEBUG.::::">My Dashboard</a>',
'            </div>',
'        </section>',
'        <!-- Contact-->',
'        <section class="page-section" id="contact">',
'            <div class="container px-4 px-lg-5">',
'                <div class="row gx-4 gx-lg-5 justify-content-center">',
'                    <div class="col-lg-8 col-xl-6 text-center">',
'                        <h2 class="mt-0">Let''s Get In Touch!</h2>',
'                        <hr class="divider" />',
'                        <p class="text-muted mb-5">Nam egestas sapien neque, sed sodales tellus tincidunt vel. Nullam varius odio at arcu interdum dignissim. Pellentesque id convallis ipsum</p>',
'                    </div>',
'                </div> ',
'                <div class="row gx-4 gx-lg-5 justify-content-center">',
'                    <div class="col-lg-4 text-center mb-5 mb-lg-0">',
'                        <i class="bi-phone fs-2 mb-3 text-muted"></i>',
'                        <div>+1.800.633.0738</div>',
'                    </div>',
'                </div>',
'            </div>',
'        </section>',
'        <!-- Footer-->',
'',
'        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>',
'<script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>',
'<script src="#APP_FILES#templates/replace-this/js/scripts.js"></script>'))
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp.component_end;
end;
/
