prompt --application/pages/page_00050
begin
--   Manifest
--     PAGE: 00050
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>7477895910065199
,p_default_application_id=>114
,p_default_id_offset=>8992108442064454
,p_default_owner=>'DEMOUSER'
);
wwv_flow_imp_page.create_page(
 p_id=>50
,p_name=>'Bankers'
,p_alias=>'BANKERS'
,p_step_title=>'Bankers'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'OFF'
,p_javascript_file_urls=>wwv_flow_string.join(wwv_flow_t_varchar2(
'',
' '))
,p_javascript_code_onload=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/*',
'setInterval("jQuery(''#static_1'').trigger(''apexrefresh'');", 20000);',
'setInterval("jQuery(''#static_5'').trigger(''apexrefresh'');", 20000); ',
'*/',
''))
,p_page_template_options=>'#DEFAULT#'
,p_overwrite_navigation_list=>'Y'
,p_navigation_list_position=>'SIDE'
,p_navigation_list_id=>wwv_flow_imp.id(501822730801075)
,p_navigation_list_template_id=>wwv_flow_imp.id(62244795433085092)
,p_nav_list_template_options=>'#DEFAULT#:t-TreeNav--styleA:js-navCollapsed--hidden'
,p_protection_level=>'C'
,p_page_component_map=>'23'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1247299391217568)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#:u-colors:t-Cards--basic:t-Cards--displayIcons:t-Cards--4cols:t-Cards--iconsRounded:t-Cards--animRaiseCard'
,p_plug_template=>wwv_flow_imp.id(62183755337085053)
,p_plug_display_sequence=>20
,p_location=>null
,p_list_id=>wwv_flow_imp.id(501822730801075)
,p_plug_source_type=>'NATIVE_LIST'
,p_list_template_id=>wwv_flow_imp.id(62232829340085084)
,p_required_patch=>wwv_flow_imp.id(62079878348084960)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(63669369183150290)
,p_plug_name=>'Banker'
,p_plug_display_sequence=>10
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>',
'<!-- Google fonts-->',
'<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />',
'<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" /> ',
'<link href="#APP_FILES#templates/startbootstrap-agency-gh-pages/css/styles.css" rel="stylesheet" />',
'',
'<!-- Navigation-->',
'        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">',
'            <div class="container">',
'                <a class="navbar-brand" href="#page-top"><img src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/navbar-logo.svg" alt="..." /></a>',
'                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">',
'                    Menu',
'                    <i class="fas fa-bars ms-1"></i>',
'                </button>',
'                <div class="collapse navbar-collapse" id="navbarResponsive">',
'                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">',
'                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>',
'                        <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>',
'                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>',
'                        <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>',
'                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>',
'                    </ul>',
'                </div>',
'            </div>',
'        </nav>',
'        <!-- Masthead-->',
'        <header class="masthead">',
'            <div class="container">',
'                <div class="masthead-subheading">Welcome To Our Studio!</div>',
'                <div class="masthead-heading text-uppercase">It''s Nice To Meet You</div>',
'                <a class="btn btn-primary btn-xl text-uppercase" href="#services">Tell Me More</a>',
'            </div>',
'        </header>',
'        <!-- Services-->',
'        <section class="page-section" id="services">',
'            <div class="container">',
'                <div class="text-center">',
'                    <h2 class="section-heading text-uppercase">Services</h2>',
'                    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>',
'                </div>',
'                <div class="row text-center">',
'                    <div class="col-md-4">',
'                        <span class="fa-stack fa-4x">',
'                            <i class="fas fa-circle fa-stack-2x text-primary"></i>',
'                            <i class="fas fa-shopping-cart fa-stack-1x fa-inverse"></i>',
'                        </span>',
'                        <h4 class="my-3">E-Commerce</h4>',
'                        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>',
'                    </div>',
'                    <div class="col-md-4">',
'                        <span class="fa-stack fa-4x">',
'                            <i class="fas fa-circle fa-stack-2x text-primary"></i>',
'                            <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>',
'                        </span>',
'                        <h4 class="my-3">Responsive Design</h4>',
'                        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>',
'                    </div>',
'                    <div class="col-md-4">',
'                        <span class="fa-stack fa-4x">',
'                            <i class="fas fa-circle fa-stack-2x text-primary"></i>',
'                            <i class="fas fa-lock fa-stack-1x fa-inverse"></i>',
'                        </span>',
'                        <h4 class="my-3">Web Security</h4>',
'                        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>',
'                    </div>',
'                </div>',
'            </div>',
'        </section>',
'        <!-- Portfolio Grid-->',
'        <section class="page-section bg-light" id="portfolio">',
'            <div class="container">',
'                <div class="text-center">',
'                    <h2 class="section-heading text-uppercase">Portfolio</h2>',
'                    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>',
'                </div>',
'                <div class="row">',
'                    <div class="col-lg-4 col-sm-6 mb-4">',
'                        <!-- Portfolio item 1-->',
'                        <div class="portfolio-item">',
'                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal1">',
'                                <div class="portfolio-hover">',
'                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>',
'                                </div>',
'                                <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/1.jpg" alt="..." />',
'                            </a>',
'                            <div class="portfolio-caption">',
'                                <div class="portfolio-caption-heading">Threads</div>',
'                                <div class="portfolio-caption-subheading text-muted">Illustration</div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6 mb-4">',
'                        <!-- Portfolio item 2-->',
'                        <div class="portfolio-item">',
'                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal2">',
'                                <div class="portfolio-hover">',
'                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>',
'                                </div>',
'                                <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/2.jpg" alt="..." />',
'                            </a>',
'                            <div class="portfolio-caption">',
'                                <div class="portfolio-caption-heading">Explore</div>',
'                                <div class="portfolio-caption-subheading text-muted">Graphic Design</div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6 mb-4">',
'                        <!-- Portfolio item 3-->',
'                        <div class="portfolio-item">',
'                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal3">',
'                                <div class="portfolio-hover">',
'                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>',
'                                </div>',
'                                <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/3.jpg" alt="..." />',
'                            </a>',
'                            <div class="portfolio-caption">',
'                                <div class="portfolio-caption-heading">Finish</div>',
'                                <div class="portfolio-caption-subheading text-muted">Identity</div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6 mb-4 mb-lg-0">',
'                        <!-- Portfolio item 4-->',
'                        <div class="portfolio-item">',
'                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal4">',
'                                <div class="portfolio-hover">',
'                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>',
'                                </div>',
'                                <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/4.jpg" alt="..." />',
'                            </a>',
'                            <div class="portfolio-caption">',
'                                <div class="portfolio-caption-heading">Lines</div>',
'                                <div class="portfolio-caption-subheading text-muted">Branding</div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6 mb-4 mb-sm-0">',
'                        <!-- Portfolio item 5-->',
'                        <div class="portfolio-item">',
'                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal5">',
'                                <div class="portfolio-hover">',
'                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>',
'                                </div>',
'                                <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/5.jpg" alt="..." />',
'                            </a>',
'                            <div class="portfolio-caption">',
'                                <div class="portfolio-caption-heading">Southwest</div>',
'                                <div class="portfolio-caption-subheading text-muted">Website Design</div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-4 col-sm-6">',
'                        <!-- Portfolio item 6-->',
'                        <div class="portfolio-item">',
'                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal6">',
'                                <div class="portfolio-hover">',
'                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>',
'                                </div>',
'                                <img class="img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/6.jpg" alt="..." />',
'                            </a>',
'                            <div class="portfolio-caption">',
'                                <div class="portfolio-caption-heading">Window</div>',
'                                <div class="portfolio-caption-subheading text-muted">Photography</div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'        </section>',
'        <!-- About-->',
'        <section class="page-section" id="about">',
'            <div class="container">',
'                <div class="text-center">',
'                    <h2 class="section-heading text-uppercase">About</h2>',
'                    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>',
'                </div>',
'                <ul class="timeline">',
'                    <li>',
'                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/about/1.jpg" alt="..." /></div>',
'                        <div class="timeline-panel">',
'                            <div class="timeline-heading">',
'                                <h4>2009-2011</h4>',
'                                <h4 class="subheading">Our Humble Beginnings</h4>',
'                            </div>',
'                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidun'
||'t et ea quo dolore laudantium consectetur!</p></div>',
'                        </div>',
'                    </li>',
'                    <li class="timeline-inverted">',
'                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/about/2.jpg" alt="..." /></div>',
'                        <div class="timeline-panel">',
'                            <div class="timeline-heading">',
'                                <h4>March 2011</h4>',
'                                <h4 class="subheading">An Agency is Born</h4>',
'                            </div>',
'                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidun'
||'t et ea quo dolore laudantium consectetur!</p></div>',
'                        </div>',
'                    </li>',
'                    <li>',
'                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/about/3.jpg" alt="..." /></div>',
'                        <div class="timeline-panel">',
'                            <div class="timeline-heading">',
'                                <h4>December 2015</h4>',
'                                <h4 class="subheading">Transition to Full Service</h4>',
'                            </div>',
'                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidun'
||'t et ea quo dolore laudantium consectetur!</p></div>',
'                        </div>',
'                    </li>',
'                    <li class="timeline-inverted">',
'                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/about/4.jpg" alt="..." /></div>',
'                        <div class="timeline-panel">',
'                            <div class="timeline-heading">',
'                                <h4>July 2020</h4>',
'                                <h4 class="subheading">Phase Two Expansion</h4>',
'                            </div>',
'                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidun'
||'t et ea quo dolore laudantium consectetur!</p></div>',
'                        </div>',
'                    </li>',
'                    <li class="timeline-inverted">',
'                        <div class="timeline-image">',
'                            <h4>',
'                                Be Part',
'                                <br />',
'                                Of Our',
'                                <br />',
'                                Story!',
'                            </h4>',
'                        </div>',
'                    </li>',
'                </ul>',
'            </div>',
'        </section>',
'        <!-- Team-->',
'        <section class="page-section bg-light" id="team">',
'            <div class="container">',
'                <div class="text-center">',
'                    <h2 class="section-heading text-uppercase">Our Amazing Team</h2>',
'                    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>',
'                </div>',
'                <div class="row">',
'                    <div class="col-lg-4">',
'                        <div class="team-member">',
'                            <img class="mx-auto rounded-circle" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/team/1.jpg" alt="..." />',
'                            <h4>Parveen Anand</h4>',
'                            <p class="text-muted">Lead Designer</p>',
'                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Twitter Profile"><i class="fab fa-twitter"></i></a>',
'                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Facebook Profile"><i class="fab fa-facebook-f"></i></a>',
'                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-4">',
'                        <div class="team-member">',
'                            <img class="mx-auto rounded-circle" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/team/2.jpg" alt="..." />',
'                            <h4>Diana Petersen</h4>',
'                            <p class="text-muted">Lead Marketer</p>',
'                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Twitter Profile"><i class="fab fa-twitter"></i></a>',
'                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Facebook Profile"><i class="fab fa-facebook-f"></i></a>',
'                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>',
'                        </div>',
'                    </div>',
'                    <div class="col-lg-4">',
'                        <div class="team-member">',
'                            <img class="mx-auto rounded-circle" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/team/3.jpg" alt="..." />',
'                            <h4>Larry Parker</h4>',
'                            <p class="text-muted">Lead Developer</p>',
'                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Twitter Profile"><i class="fab fa-twitter"></i></a>',
'                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Facebook Profile"><i class="fab fa-facebook-f"></i></a>',
'                            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>',
'                        </div>',
'                    </div>',
'                </div>',
'                <div class="row">',
'                    <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p><'
||'/div>',
'                </div>',
'            </div>',
'        </section>',
'        <!-- Clients-->',
'        <div class="py-5">',
'            <div class="container">',
'                <div class="row align-items-center">',
'                    <div class="col-md-3 col-sm-6 my-3">',
'                        <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/logos/microsoft.svg" alt="..." aria-label="Microsoft Logo" /></a>',
'                    </div>',
'                    <div class="col-md-3 col-sm-6 my-3">',
'                        <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/logos/google.svg" alt="..." aria-label="Google Logo" /></a>',
'                    </div>',
'                    <div class="col-md-3 col-sm-6 my-3">',
'                        <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/logos/facebook.svg" alt="..." aria-label="Facebook Logo" /></a>',
'                    </div>',
'                    <div class="col-md-3 col-sm-6 my-3">',
'                        <a href="#!"><img class="img-fluid img-brand d-block mx-auto" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/logos/ibm.svg" alt="..." aria-label="IBM Logo" /></a>',
'                    </div>',
'                </div>',
'            </div>',
'        </div>',
'        <!-- Contact-->',
'          ',
'        <!-- Portfolio item 1 modal popup-->',
'        <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">',
'            <div class="modal-dialog">',
'                <div class="modal-content">',
'                    <div class="close-modal" data-bs-dismiss="modal"><img src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/close-icon.svg" alt="Close modal" /></div>',
'                    <div class="container">',
'                        <div class="row justify-content-center">',
'                            <div class="col-lg-8">',
'                                <div class="modal-body">',
'                                    <!-- Project details-->',
'                                    <h2 class="text-uppercase">Project Name</h2>',
'                                    <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>',
'                                    <img class="img-fluid d-block mx-auto" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/1.jpg" alt="..." />',
'                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita bea'
||'tae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>',
'                                    <ul class="list-inline">',
'                                        <li>',
'                                            <strong>Client:</strong>',
'                                            Threads',
'                                        </li>',
'                                        <li>',
'                                            <strong>Category:</strong>',
'                                            Illustration',
'                                        </li>',
'                                    </ul>',
'                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">',
'                                        <i class="fas fa-xmark me-1"></i>',
'                                        Close Project',
'                                    </button>',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'        </div>',
'        <!-- Portfolio item 2 modal popup-->',
'        <div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">',
'            <div class="modal-dialog">',
'                <div class="modal-content">',
'                    <div class="close-modal" data-bs-dismiss="modal"><img src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/close-icon.svg" alt="Close modal" /></div>',
'                    <div class="container">',
'                        <div class="row justify-content-center">',
'                            <div class="col-lg-8">',
'                                <div class="modal-body">',
'                                    <!-- Project details-->',
'                                    <h2 class="text-uppercase">Project Name</h2>',
'                                    <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>',
'                                    <img class="img-fluid d-block mx-auto" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/2.jpg" alt="..." />',
'                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita bea'
||'tae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>',
'                                    <ul class="list-inline">',
'                                        <li>',
'                                            <strong>Client:</strong>',
'                                            Explore',
'                                        </li>',
'                                        <li>',
'                                            <strong>Category:</strong>',
'                                            Graphic Design',
'                                        </li>',
'                                    </ul>',
'                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">',
'                                        <i class="fas fa-xmark me-1"></i>',
'                                        Close Project',
'                                    </button>',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'        </div>',
'        <!-- Portfolio item 3 modal popup-->',
'        <div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true">',
'            <div class="modal-dialog">',
'                <div class="modal-content">',
'                    <div class="close-modal" data-bs-dismiss="modal"><img src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/close-icon.svg" alt="Close modal" /></div>',
'                    <div class="container">',
'                        <div class="row justify-content-center">',
'                            <div class="col-lg-8">',
'                                <div class="modal-body">',
'                                    <!-- Project details-->',
'                                    <h2 class="text-uppercase">Project Name</h2>',
'                                    <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>',
'                                    <img class="img-fluid d-block mx-auto" src="assets/img/portfolio/3.jpg" alt="..." />',
'                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita bea'
||'tae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>',
'                                    <ul class="list-inline">',
'                                        <li>',
'                                            <strong>Client:</strong>',
'                                            Finish',
'                                        </li>',
'                                        <li>',
'                                            <strong>Category:</strong>',
'                                            Identity',
'                                        </li>',
'                                    </ul>',
'                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">',
'                                        <i class="fas fa-xmark me-1"></i>',
'                                        Close Project',
'                                    </button>',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'        </div>',
'        <!-- Portfolio item 4 modal popup-->',
'        <div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-hidden="true">',
'            <div class="modal-dialog">',
'                <div class="modal-content">',
'                    <div class="close-modal" data-bs-dismiss="modal"><img src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/close-icon.svg" alt="Close modal" /></div>',
'                    <div class="container">',
'                        <div class="row justify-content-center">',
'                            <div class="col-lg-8">',
'                                <div class="modal-body">',
'                                    <!-- Project details-->',
'                                    <h2 class="text-uppercase">Project Name</h2>',
'                                    <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>',
'                                    <img class="img-fluid d-block mx-auto" src="#APP_FILES#templates/startbootstrap-agency-gh-pages/assets/img/portfolio/4.jpg" alt="..." />',
'                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita bea'
||'tae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>',
'                                    <ul class="list-inline">',
'                                        <li>',
'                                            <strong>Client:</strong>',
'                                            Lines',
'                                        </li>',
'                                        <li>',
'                                            <strong>Category:</strong>',
'                                            Branding',
'                                        </li>',
'                                    </ul>',
'                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">',
'                                        <i class="fas fa-xmark me-1"></i>',
'                                        Close Project',
'                                    </button>',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'        </div>',
'        ',
'         ',
' <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script> ',
'<script src="#APP_FILES#templates/startbootstrap-agency-gh-pages/js/scripts.js"></script>'))
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(114795716008958780)
,p_plug_name=>'Cards1'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(62124331163085017)
,p_plug_display_sequence=>30
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select ID,',
'       LABEL_NAME,',
'       TERM1,',
'       TERM2,',
'       TERM3,',
'       TERM4,',
'       TERM5,',
'       TERM1LINK,',
'       TERM1INFO,',
'       HIGH_SCORE_LABEL,',
'       "3DURL",',
'       CONTENT_TYPE,',
'       IMAGE',
'  from RELATED_LABELS',
' where CONTENT_TYPE = ''3D_AIFS'' ',
' --AND LABEL_NAME = ''ATM Cash Withdrawal'''))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_CARDS'
,p_plug_query_num_rows_type=>'SCROLL'
,p_show_total_row_count=>false
,p_required_patch=>wwv_flow_imp.id(62079878348084960)
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_card(
 p_id=>wwv_flow_imp.id(589270225182580)
,p_region_id=>wwv_flow_imp.id(114795716008958780)
,p_layout_type=>'GRID'
,p_grid_column_count=>3
,p_title_adv_formatting=>false
,p_sub_title_adv_formatting=>false
,p_body_adv_formatting=>true
,p_body_html_expr=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<p>&LABEL_NAME.</p>',
'<div class="sketchfab-embed-wrapper"> ',
'        <iframe title="CT scan lung" frameborder="0" allowfullscreen mozallowfullscreen="true" style="width:100%;height:400px" ',
'        webkitallowfullscreen="true"',
'         allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking',
'          execution-while-out-of-viewport execution-while-not-rendered web-share ',
'          src=&3DURL.> </iframe> ',
'          </div>'))
,p_second_body_adv_formatting=>false
,p_media_adv_formatting=>false
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(590255175182593)
,p_name=>'UpdateComments'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
,p_display_when_type=>'NEVER'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(590695353182597)
,p_event_id=>wwv_flow_imp.id(590255175182593)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_EXECUTE_PLSQL_CODE'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'',
'v_id number;',
'v_this_credit_card varchar2(50);',
'v_previous_card  varchar2(50);',
'v_this_mall varchar2(50);',
'v_previous_mall varchar2(50);',
'v_time_diff_number number;',
'v_comment varchar2(500);',
'v_credit_card_no varchar2(50);',
'',
'Cursor C1 IS   ',
'    SELECT t.id, t.inv_no, t.total_pay, trans_status, comments,',
'    CREDIT_CARD_NO this_credit_card, ',
'    LAG(CREDIT_CARD_NO) OVER (ORDER BY id) AS previous_card, ',
'    MALL this_mall, ',
'    LAG(MALL) OVER (ORDER BY id) AS previous_mall,  ',
'    to_char(TX_TIMESTAMP,''dd/mm/yyyy hh24:mi:ss'') TX_TIMESTAMP,   ',
'    t.TX_TIMESTAMP - LAG(t.TX_TIMESTAMP) OVER (ORDER BY t.TX_TIMESTAMP) AS time_difference,',
'    to_char(TX_TIMESTAMP,''yyyymmddHH24MISS'') - LAG(to_char(TX_TIMESTAMP,''yyyymmddHH24MISS'')) OVER (ORDER BY to_char(TX_TIMESTAMP,''yyyymmddHH24MISS'')) AS time_diff_number ',
'    FROM RETAIL_SHOPPING_FD t where transaction_status = ''OnHold'' ',
'    order by id  desc;  ',
'',
'Cursor C2 IS ',
'     select credit_card_no from RETAIL_SHOPPING_FD where trans_status = ''BLOCK CARD'';',
' ',
'BEGIN',
'',
'    For row_1 In C1 Loop',
'       v_id := row_1.id; ',
'       v_this_credit_card := row_1.this_credit_card; ',
'       v_previous_card := row_1.previous_card; ',
'       v_this_mall := row_1.this_mall;',
'       v_previous_mall := row_1.previous_mall;',
'       v_time_diff_number := row_1.time_diff_number;',
'      -- Htp.p(''<br/> ''||v_id||'' this_credit_card ''||v_this_credit_card||'' previous_card ',
'      -- ''||v_previous_card||'' v_this_mall ''||v_this_mall||'' v_previous_mall ''||v_previous_mall);',
'',
'       ',
'        if   (v_time_diff_number <= 120) AND (v_time_diff_number > 60) AND',
'             (v_this_credit_card = v_previous_card) AND  ',
'             (v_this_mall != v_previous_mall) ',
'             then ',
'            v_comment := ''The same credit card has been reused in less than 120 seconds under different locations, ',
'                        so that card has been blocked''; ',
'            UPDATE RETAIL_SHOPPING_FD SET COMMENTS = v_comment WHERE ID = v_id;',
'        elsif   (v_time_diff_number <= 120) AND (v_time_diff_number > 60) AND',
'             (v_this_credit_card = v_previous_card) AND  ',
'             (v_this_mall = v_previous_mall) ',
'             then ',
'            v_comment := ''The same credit card has been reused in less than 120 seconds in same location, ',
'                        please verify''; ',
'            UPDATE RETAIL_SHOPPING_FD SET COMMENTS = v_comment WHERE ID = v_id;',
'        elsif (v_time_diff_number <= 60)    then',
'            v_comment := ''The same credit card has been reused in less than 60 seconds, so that card has been blocked''; ',
'            UPDATE RETAIL_SHOPPING_FD SET COMMENTS = v_comment WHERE ID = v_id;  ',
'       end if;',
'',
'    End Loop; ',
'',
'    For row_2 In C2 Loop',
'        v_credit_card_no := row_2.credit_card_no; ',
'        UPDATE CC_FD SET STATUS=''Blocked'', COMMENTS=''Blocked by Human Review'' WHERE CC_NO = v_credit_card_no;',
'    End Loop; ',
'',
'END;'))
,p_attribute_05=>'PLSQL'
,p_wait_for_result=>'Y'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(589945501182592)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'Expand'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE data clob;',
'fetch_vert_id NUMBER := round(',
'  DBMS_RANDOM.VALUE (1000, 5000)',
');',
'edge_id NUMBER := round(',
'  DBMS_RANDOM.VALUE (1000, 5000)',
');',
'BEGIN ',
'SELECT ',
'  (',
'    JSON_OBJECT(',
'      ''vertices'' VALUE JSON_ARRAY(',
'        JSON_OBJECT(',
'          ''id'' VALUE apex_application.g_x01',
'        ), ',
'        JSON_OBJECT(',
'          ''id'' VALUE fetch_vert_id, ',
'          ''properties'' VALUE JSON_OBJECT(',
'            ''FirstName'' VALUE ''Expanded'', ''LastName'' VALUE fetch_vert_id',
'          )',
'        )',
'      ), ',
'      ''edges'' VALUE JSON_ARRAY(',
'        JSON_OBJECT(',
'          ''id'' VALUE edge_id, ''source'' VALUE apex_application.g_x01, ',
'          ''target'' VALUE fetch_vert_id',
'        )',
'      )',
'    )',
'  ) INTO data ',
'FROM ',
'  SYS.DUAL;',
'htp.p(data);',
'END;',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>9582053943247046
);
wwv_flow_imp.component_end;
end;
/
