prompt --application/pages/page_00030
begin
--   Manifest
--     PAGE: 00030
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>7477895910065199
,p_default_application_id=>114
,p_default_id_offset=>8992108442064454
,p_default_owner=>'DEMOUSER'
);
wwv_flow_imp_page.create_page(
 p_id=>30
,p_name=>'ANM_REST'
,p_alias=>'ANM-REST'
,p_step_title=>'ANM_REST'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'10'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93356275733019652)
,p_plug_name=>'RG_large_dataset'
,p_region_name=>'ofcdetails'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(62183755337085053)
,p_plug_display_sequence=>40
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare ',
'',
'GC_WC_CREDENTIAL_ID        CONSTANT VARCHAR2(50)   := ''replace-this'';  ',
'GC_OCI_DOC_AI_URL          CONSTANT VARCHAR2(500)  := ''https://anomalydetection.aiservice.us-phoenix-1.oci.oraclecloud.com/20210101/detectAnomalyJobs''; ',
'BASE_URL CONSTANT VARCHAR2(500) := ''https://anomalydetection.aiservice.us-phoenix-1.oci.oraclecloud.com/20210101'';',
'compartmentId CONSTANT VARCHAR2(500) := ''ocid1.compartment.oc1..replace-this'';',
'projectId CONSTANT VARCHAR2(500) := ''ocid1.aianomalydetectionproject.oc1.phx.amaaaaaaknuwtjiapvs2awb56mryemubr4qrcfcso55y2ecjpe5cvohzlnlq'';',
'AI_URL CONSTANT VARCHAR2(500) := BASE_URL||''/models?compartmentId=''||compartmentId||''&projectId=''||projectId||''&limit=10&sortOrder=ASC&sortBy=timeCreated'';',
'json_input_str3 varchar2(4000) ;',
' ',
' ',
'',
'request_payload_small_ds   varchar2(32000)   ;',
'',
'l_request_json        VARCHAR2(32000); ',
'l_response_json       CLOB; ',
'  v_id varchar(100);',
'  v_filename varchar(100);',
'  l_obj_name varchar2(500);',
'  l_base_path varchar2(500) := ''https://objectstorage.us-phoenix-1.oraclecloud.com/n/replace-this/b/replace-this/o/'';',
'  l_docjob_json_url varchar2(4000) ;',
'  l_json                CLOB;',
'  v_time_diff number := 1; ',
'  v_tx_timestamp FD_TX_HISTORIC_DATA.TX_TIMESTAMP%TYPE;',
'  v_total_pay FD_TX_HISTORIC_DATA.TOTAL_PAY%TYPE;',
'',
'  cursor c1 is ',
'      SELECT  JSON_ARRAYAGG(',
'                 JSON_OBJECT',
'                 (',
'                        ''timestamp'' VALUE TO_CHAR((  TX_TIMESTAMP  ), ''YYYY-MM-DD"T"HH24:MI:SS".000Z"'' ), ',
'                        ''values'' VALUE json_array(TOTAL_PAY)   ',
'                ) ORDER BY TX_TIMESTAMP   )  as TX_DATA  ',
'FROM FD_TX_HISTORIC_DATA  ;',
'',
'cursor c2 is ',
'      SELECT   TX_TIMESTAMP,  TOTAL_PAY ',
'        FROM FD_TX_HISTORIC_DATA order by TX_TIMESTAMP ;',
'  ',
'begin  ',
'  Htp.p(GC_OCI_DOC_AI_URL);',
'  Htp.p(''<br/><hr/>'');',
'  Htp.p(request_payload_small_ds);',
'  Htp.p(''<br/><hr/>'');',
'',
'  delete from FD_TX_HISTORIC_DATA;',
'',
'  FOR Lcntr IN 1..7 LOOP',
'         v_total_pay := round(DBMS_Random.Value(1,12000),0);  ',
'         FD_TX_HISTORICDATA_INSERTS (v_time_diff, v_total_pay);',
'        v_time_diff := v_time_diff + 1;',
'   END LOOP;',
'',
'   FOR Lcntr2 IN 1..7 LOOP',
'         v_total_pay := round(DBMS_Random.Value(1,55000),0);  ',
'         FD_TX_HISTORICDATA_INSERTS (v_time_diff, v_total_pay);',
'        v_time_diff := v_time_diff + 1;',
'   END LOOP;',
'',
'    Htp.p(''<table border=1>'');',
'    For row_2 In C2 Loop',
'       v_tx_timestamp := row_2.TX_TIMESTAMP; ',
'       v_total_pay := row_2.TOTAL_PAY; ',
'       Htp.p(''<tr><td>''||v_tx_timestamp||''</td><td>''||v_total_pay||''</td></tr>'');',
'    End Loop;',
'    Htp.p(''</table>'');',
'',
'    For row_1 In C1 Loop',
'       json_input_str3 := row_1.TX_DATA; ',
'    End Loop;',
'',
'    request_payload_small_ds   := ''',
'                        {',
'                          "compartmentId": "ocid1.compartment.oc1..replace-this",',
'                          "description": "AD",',
'                          "displayName": "AD",',
'                          "modelId": "ocid1.aianomalydetectionmodel.oc1.phx.amaaaaaaknuwtjiaapusfv6pxavfbxm546pan2phqh54j2p64j2ys7inkofq",',
'                          "inputDetails": {',
'                              "inputType": "INLINE",',
'                                "signalNames":["TOTAL_PAY"],',
'                                    "data":   ''||json_input_str3||''',
'                                  },',
'                         "outputDetails": {',
'                               "namespaceName": "replace-this",',
'                            "bucketName": "replace-this",',
'                            "outputType": "OBJECT_STORAGE",',
'                            "prefix": "AA"',
'                            } ',
'                        }',
'                        '';',
'  ',
'  apex_web_service.g_request_headers.DELETE; ',
'  apex_web_service.g_request_headers(1).name  := ''Content-Type''; ',
'  apex_web_service.g_request_headers(1).value := ''application/json''; ',
' ',
'  -- Call the Document AI analyzeDocument REST Web Service. ',
'        l_response_json := apex_web_service.make_rest_request ',
'        (p_url                  => GC_OCI_DOC_AI_URL, ',
'        p_http_method          => ''POST'', ',
'        p_body                 => request_payload_small_ds, ',
'        p_credential_static_id => GC_WC_CREDENTIAL_ID);',
'',
'        Htp.p(l_response_json);',
'',
'        apex_json.parse (l_response_json);',
'        v_id := apex_json.get_varchar2 (''id'');',
'',
'        --For row_1 In C1 Loop',
'         --      v_filename := row_1.file_name; ',
'        --End Loop;',
'        /*',
'        https://objectstorage.us-phoenix-1.oraclecloud.com/n/replace-this/b/replace-this/o/',
'        AA%2Focid1.aianomalydetectionjob.oc1.phx.amaaaaaaknuwtjiabf6khhtdk3nld3wzkelaiidhz4fytettrybkmvkeub2a%2Focid1.aianomalydetectionjob.oc1.phx.amaaaaaaknuwtjiabf6khhtdk3nld3wzkelaiidhz4fytettrybkmvkeub2a-result.json',
'        */',
'',
'        l_docjob_json_url   := l_base_path||''AA/''||v_id||''/''||v_id||''-result.json'';',
'',
'       --apex.message.showPageSuccess( "Changes saved!" );',
'',
'       --DBMS_LOCK.sleep(120);',
'',
'        Htp.p(''<br/><br/><a href=''||l_docjob_json_url||''>download</a>'');',
'',
'',
'        ',
'        ',
'        ',
'',
'        /*',
'',
'        request_payload_small_ds constant varchar2(32000) := ''',
'{',
'  "compartmentId": "ocid1.compartment.oc1..replace-this",',
'  "description": "AD",',
'  "displayName": "AD",',
'  "modelId": "ocid1.aianomalydetectionmodel.oc1.phx.amaaaaaaknuwtjiaapusfv6pxavfbxm546pan2phqh54j2p64j2ys7inkofq",',
'  "inputDetails": {',
'      "inputType": "INLINE",',
'        "signalNames":["TOTAL_PAY"],',
'            "data":  [{',
'                    "timestamp": "2020-07-13T18:54:11.000Z",',
'                    "values": [ 1111  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:12.000Z",',
'                    "values": [ 2222  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:13.000Z",',
'                    "values": [ 122222  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:14.000Z",',
'                    "values": [ 2222  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:15.000Z",',
'                    "values": [ 2222  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:16.000Z",',
'                    "values": [ 122244  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:17.000Z",',
'                    "values": [ 1245  ]',
'                }]',
'          },',
' "outputDetails": {',
'       "namespaceName": "replace-this",',
'    "bucketName": "replace-this",',
'    "outputType": "OBJECT_STORAGE",',
'    "prefix": "AA"',
'    } ',
'}',
''';',
'',
'',
'         l_json := apex_web_service.make_rest_request',
'             (p_url => UTL_URL.ESCAPE(l_docjob_json_url),',
'              p_http_method => ''GET'',',
'              p_credential_static_id => GC_WC_CREDENTIAL_ID);',
'              ',
'',
'',
'              Htp.p(l_json);',
'              ',
'                {',
'                    "timestamp": "2020-07-13T18:54:11.000Z",',
'                    "values": [ 1111  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:12.000Z",',
'                    "values": [ 2222  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:13.000Z",',
'                    "values": [ 122222  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:14.000Z",',
'                    "values": [ 2222  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:15.000Z",',
'                    "values": [ 2222  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:16.000Z",',
'                    "values": [ 122244  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:17.000Z",',
'                    "values": [ 1245  ]',
'                }',
'         */',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
,p_plug_display_condition_type=>'NEVER'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93356345200019653)
,p_plug_name=>'RG'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(62183755337085053)
,p_plug_display_sequence=>60
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare ',
'',
'GC_WC_CREDENTIAL_ID        CONSTANT VARCHAR2(50)   := ''replace-this'';  ',
'GC_OCI_DOC_AI_URL          CONSTANT VARCHAR2(500)  := ''https://anomalydetection.aiservice.us-phoenix-1.oci.oraclecloud.com/20210101/detectAnomalyJobs''; ',
'--models?compartmentId={{compartment_ocid}}&projectId=ocid1.aianomalydetectionproject.oc1.phx.amaaaaaaknuwtjiapvs2awb56mryemubr4qrcfcso55y2ecjpe5cvohzlnlq&limit=10&sortOrder=ASC&sortBy=timeCreated',
'--https://docs.oracle.com/en-us/iaas/api/#/en/anomalydetection/20210101/datatypes/CreateDetectAnomalyJobDetails',
'-- https://docs.oracle.com/en-us/iaas/Content/anomaly/using/detect-anomalies-using-async-inference.htm',
'BASE_URL CONSTANT VARCHAR2(500) := ''https://anomalydetection.aiservice.us-phoenix-1.oci.oraclecloud.com/20210101'';',
'compartmentId CONSTANT VARCHAR2(500) := ''ocid1.compartment.oc1..replace-this'';',
'projectId CONSTANT VARCHAR2(500) := ''ocid1.aianomalydetectionproject.oc1.phx.amaaaaaaknuwtjiapvs2awb56mryemubr4qrcfcso55y2ecjpe5cvohzlnlq'';',
'AI_URL CONSTANT VARCHAR2(500) := BASE_URL||''/models?compartmentId=''||compartmentId||''&projectId=''||projectId||''&limit=10&sortOrder=ASC&sortBy=timeCreated'';',
'',
'',
'request_payload constant varchar2(32000) := ''',
'{',
'  "compartmentId": "ocid1.compartment.oc1..replace-this",',
'  "description": AD,',
'  "displayName": AD,',
'  "modelId": "ocid1.aimodel.oc1.phx.amaaaaaaor7l3jialglh5vnt2w3nj6zly4dpcjfex6lktujo24t5aklmn2ta",',
'  "inputDetails": {',
'      "inputType": "INLINE",',
'      "signalNames":["sensor1"],',
'        "data": [',
'            {',
'                "timestamp": "2019-01-01T01:02:01.000+00:0",',
'                "values": [ 23445]',
'            },',
'            {',
'                "timestamp": "2019-01-01T01:02:02.000+00:0",',
'                "values": [ 7699]',
'            },',
'            {',
'                "timestamp": "2019-01-01T01:02:03.000+00:0",',
'                "values": [ 212333]',
'            } ',
'        ]',
'  },',
'  "outputDetails": {',
'    "outputType": "OBJECT_STORAGE",',
'    "namespaceName": "replace-this",',
'    "bucketName": "replace-this",',
'    "prefix": "test-prefix"',
'  }',
'}',
''';',
'',
'l_request_json        VARCHAR2(32000); ',
'  l_response_json       CLOB; ',
'',
'  /*',
'  {',
'    "inputType": "OBJECT_LIST",',
'    "objectLocations": [',
'      {',
'            "namespaceName": "replace-this",',
'            "bucketName": "replace-this",',
'            "objectName": "Anomaly/finserv_test_data_2.csv"',
'      } ',
'    ]',
'  }',
'  */',
'',
'--/20210101/detectAnomalyJobs',
'/*',
'compartment_id="ocid1.test.oc1..<unique_ID>EXAMPLE-compartmentId-Value",',
'        model_id="ocid1.test.oc1..<unique_ID>EXAMPLE-modelId-Value",',
'        input_details=oci.ai_anomaly_detection.models.ObjectListInputDetails(',
'            input_type="OBJECT_LIST",',
'            object_locations=[',
'                oci.ai_anomaly_detection.models.ObjectLocation(',
'                    namespace_name="EXAMPLE-namespaceName-Value",',
'                    bucket_name="EXAMPLE-bucketName-Value",',
'                    object_name="EXAMPLE-objectName-Value")]),',
'        output_details=oci.ai_anomaly_detection.models.ObjectStoreOutputDetails(',
'            output_type="OBJECT_STORAGE",',
'            namespace_name="EXAMPLE-namespaceName-Value",',
'            bucket_name="EXAMPLE-bucketName-Value",',
'            prefix="EXAMPLE-prefix-Value"),',
'        description="EXAMPLE-description-Value",',
'        display_name="EXAMPLE-displayName-Value",',
'        sensitivity=0.7275206,',
'        are_all_estimates_required=True),',
'    opc_request_id="LRTOA8THHNHYKAVUBNAU<unique_ID>",',
'    opc_retry_token="EXAMPLE-opcRetryToken-Value")',
'    GC_OCY_DOC_AI_PAYLOAD      CONSTANT VARCHAR2(32000) := ''{',
'    "areAllEstimatesRequired":"no",',
'    "compartmentId": "ocid1.compartment.oc1..replace-this",',
'    "modelId": "ocid1.aimodel.oc1.phx.amaaaaaaor7l3jialglh5vnt2w3nj6zly4dpcjfex6lktujo24t5aklmn2ta",   ',
'    "inputDetails": { ',
'                "inputType": "OBJECT_LIST",',
'                "namespaceName": "replace-this",',
'                "bucketName": "replace-this",',
'                "objectName": "Anomaly/finserv_test_data_2.csv"  ',
'                },',
'    "outputDetails": {  ',
'            "outputType" : "OBJECT_LIST",',
'            "prefix" : "AAA", ',
'            "namespaceName": "replace-this",',
'            "bucketName": "replace-this" ',
'    }',
'}''; ',
'    */',
'',
'begin ',
'-- Set Content-Type in the Request Header. This is required by the Document AI REST Service. ',
'  Htp.p(AI_URL);',
'  ',
'  apex_web_service.g_request_headers.DELETE; ',
'  apex_web_service.g_request_headers(1).name  := ''Content-Type''; ',
'  apex_web_service.g_request_headers(1).value := ''application/json''; ',
' ',
'  -- Call the Document AI analyzeDocument REST Web Service. ',
'        l_response_json := apex_web_service.make_rest_request ',
'        (p_url                  => AI_URL, ',
'        p_http_method          => ''GET'', ',
'        --p_body                 => GC_OCY_DOC_AI_PAYLOAD, ',
'        p_credential_static_id => GC_WC_CREDENTIAL_ID);',
'',
'        Htp.p(l_response_json);',
'       ',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
,p_plug_display_condition_type=>'NEVER'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93356454108019654)
,p_plug_name=>'RG_small_dataset'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(62183755337085053)
,p_plug_display_sequence=>50
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare ',
'',
'GC_WC_CREDENTIAL_ID        CONSTANT VARCHAR2(50)   := ''replace-this'';  ',
'GC_OCI_DOC_AI_URL          CONSTANT VARCHAR2(500)  := ''https://anomalydetection.aiservice.us-phoenix-1.oci.oraclecloud.com/20210101/detectAnomalyJobs''; ',
'--models?compartmentId={{compartment_ocid}}&projectId=ocid1.aianomalydetectionproject.oc1.phx.amaaaaaaknuwtjiapvs2awb56mryemubr4qrcfcso55y2ecjpe5cvohzlnlq&limit=10&sortOrder=ASC&sortBy=timeCreated',
'--https://docs.oracle.com/en-us/iaas/api/#/en/anomalydetection/20210101/datatypes/CreateDetectAnomalyJobDetails',
'-- https://docs.oracle.com/en-us/iaas/Content/anomaly/using/detect-anomalies-using-async-inference.htm',
'BASE_URL CONSTANT VARCHAR2(500) := ''https://anomalydetection.aiservice.us-phoenix-1.oci.oraclecloud.com/20210101'';',
'compartmentId CONSTANT VARCHAR2(500) := ''ocid1.compartment.oc1..replace-this'';',
'projectId CONSTANT VARCHAR2(500) := ''ocid1.aianomalydetectionproject.oc1.phx.amaaaaaaknuwtjiapvs2awb56mryemubr4qrcfcso55y2ecjpe5cvohzlnlq'';',
'AI_URL CONSTANT VARCHAR2(500) := BASE_URL||''/models?compartmentId=''||compartmentId||''&projectId=''||projectId||''&limit=10&sortOrder=ASC&sortBy=timeCreated'';',
'',
'',
'request_payload constant varchar2(32000) := ''',
'{',
'  "compartmentId": "ocid1.compartment.oc1..replace-this",',
'  "description": "AD",',
'  "displayName": "AD",',
'  "modelId": "ocid1.aianomalydetectionmodel.oc1.phx.amaaaaaaknuwtjiaapusfv6pxavfbxm546pan2phqh54j2p64j2ys7inkofq",',
'  "inputDetails": {',
'      "inputType": "INLINE",',
'        "signalNames":["TOTAL_PAY"],',
'            "data": [',
'                {',
'                    "timestamp": "2020-07-13T18:54:46.000Z",',
'                    "values": [ 0.2282  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:55:46.000Z",',
'                    "values": [ -0.4359  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:56:46.000Z",',
'                    "values": [ -0.7482 ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:57:46.000Z",',
'                    "values": [ 0.2655  ]',
'                },',
'                {',
'                    "timestamp": "2020-07-13T18:58:46.000Z",',
'                    "values": [ -0.6848  ]',
'                }',
'            ]',
'          },',
' "outputDetails": {',
'       "namespaceName": "replace-this",',
'    "bucketName": "replace-this",',
'    "outputType": "OBJECT_STORAGE",',
'    "prefix": "AA"',
'    } ',
'}',
''';',
'',
'l_request_json        VARCHAR2(32000); ',
'  l_response_json       CLOB; ',
'',
'  /*',
'  {',
'    "inputType": "OBJECT_LIST",',
'    "objectLocations": [',
'      {',
'            "namespaceName": "replace-this",',
'            "bucketName": "replace-this",',
'            "objectName": "Anomaly/finserv_test_data_2.csv"',
'      } ',
'    ]',
'  }',
'  */',
'',
'--/20210101/detectAnomalyJobs',
'/*',
'compartment_id="ocid1.test.oc1..<unique_ID>EXAMPLE-compartmentId-Value",',
'        model_id="ocid1.test.oc1..<unique_ID>EXAMPLE-modelId-Value",',
'        input_details=oci.ai_anomaly_detection.models.ObjectListInputDetails(',
'            input_type="OBJECT_LIST",',
'            object_locations=[',
'                oci.ai_anomaly_detection.models.ObjectLocation(',
'                    namespace_name="EXAMPLE-namespaceName-Value",',
'                    bucket_name="EXAMPLE-bucketName-Value",',
'                    object_name="EXAMPLE-objectName-Value")]),',
'        output_details=oci.ai_anomaly_detection.models.ObjectStoreOutputDetails(',
'            output_type="OBJECT_STORAGE",',
'            namespace_name="EXAMPLE-namespaceName-Value",',
'            bucket_name="EXAMPLE-bucketName-Value",',
'            prefix="EXAMPLE-prefix-Value"),',
'        description="EXAMPLE-description-Value",',
'        display_name="EXAMPLE-displayName-Value",',
'        sensitivity=0.7275206,',
'        are_all_estimates_required=True),',
'    opc_request_id="LRTOA8THHNHYKAVUBNAU<unique_ID>",',
'    opc_retry_token="EXAMPLE-opcRetryToken-Value")',
'    GC_OCY_DOC_AI_PAYLOAD      CONSTANT VARCHAR2(32000) := ''{',
'    "areAllEstimatesRequired":"no",',
'    "compartmentId": "ocid1.compartment.oc1..replace-this",',
'    "modelId": "ocid1.aimodel.oc1.phx.amaaaaaaor7l3jialglh5vnt2w3nj6zly4dpcjfex6lktujo24t5aklmn2ta",   ',
'    "inputDetails": { ',
'                "inputType": "OBJECT_LIST",',
'                "namespaceName": "replace-this",',
'                "bucketName": "replace-this",',
'                "objectName": "Anomaly/finserv_test_data_2.csv"  ',
'                },',
'    "outputDetails": {  ',
'            "outputType" : "OBJECT_LIST",',
'            "prefix" : "AAA", ',
'            "namespaceName": "replace-this",',
'            "bucketName": "replace-this" ',
'    }',
'}''; ',
'    */',
'',
'begin ',
'-- Set Content-Type in the Request Header. This is required by the Document AI REST Service. ',
'  Htp.p(GC_OCI_DOC_AI_URL);',
'  Htp.p(''<br/><hr/>'');',
'  Htp.p(request_payload);',
'  Htp.p(''<br/><hr/>'');',
'  ',
'  apex_web_service.g_request_headers.DELETE; ',
'  apex_web_service.g_request_headers(1).name  := ''Content-Type''; ',
'  apex_web_service.g_request_headers(1).value := ''application/json''; ',
' ',
'  -- Call the Document AI analyzeDocument REST Web Service. ',
'        l_response_json := apex_web_service.make_rest_request ',
'        (p_url                  => GC_OCI_DOC_AI_URL, ',
'        p_http_method          => ''POST'', ',
'        p_body                 => request_payload, ',
'        p_credential_static_id => GC_WC_CREDENTIAL_ID);',
'',
'        Htp.p(l_response_json);',
'         ',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
,p_plug_display_condition_type=>'NEVER'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93356618722019655)
,p_plug_name=>'Timeseries'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(62183755337085053)
,p_plug_display_sequence=>30
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'v_TX_TIMESTAMP   FD_TX_HISTORIC_DATA.TX_TIMESTAMP%TYPE; ',
'v_TOTAL_PAY FD_TX_HISTORIC_DATA.TOTAL_PAY%TYPE; ',
'v_time_diff number := 1; ',
'v_tz timestamp;',
'Cursor C1 is select * from FD_TX_HISTORIC_DATA;',
'',
'/*',
'json_input_str varchar2(4000) := ''[',
'        {"timestamp":"2023-11-22T08:10:11.000Z","values":[ 8329 ]},',
'        {"timestamp":"2023-11-22T08:10:12.000Z","values":[ 9672 ]},',
'        {"timestamp":"2023-11-22T08:10:13.000Z","values":[ 8263 ]},',
'        {"timestamp":"2023-11-22T08:10:14.000Z","values":[ 105511 ]},',
'        {"timestamp":"2023-11-22T08:10:15.000Z","values":[ 6895 ]},',
'        {"timestamp":"2023-11-22T08:10:16.000Z","values":[ 1055649 ]},',
'        {"timestamp":"2023-11-22T08:10:17.000Z","values":[ 6895 ]},',
'        {"timestamp":"2023-11-22T08:10:18.000Z","values":[ 8329 ]},',
'        {"timestamp":"2023-11-22T08:10:19.000Z","values":[ 9672 ]},',
'        {"timestamp":"2023-11-22T08:10:20.000Z","values":[ 8263 ]},',
'        {"timestamp":"2023-11-22T08:10:21.000Z","values":[ 105511 ]},',
'        {"timestamp":"2023-11-22T08:10:22.000Z","values":[ 6895 ]},',
'        {"timestamp":"2023-11-22T08:10:23.000Z","values":[ 1055649 ]},',
'        {"timestamp":"2023-11-22T08:10:24.000Z","values":[ 6895 ]}',
']'';',
'',
'[{"timestamp":"2023-11-22T14:16:35.000Z","values":[1456]},{"timestamp":"2023-11-22T14:16:36.000Z","values":[1594]},{"timestamp":"2023-11-22T14:16:37.000Z","values":[566]},{"timestamp":"2023-11-22T14:16:38.000Z","values":[1063]},{"timestamp":"2023-11-'
||'22T14:16:39.000Z","values":[335]},{"timestamp":"2023-11-22T14:16:40.000Z","values":[2449]},{"timestamp":"2023-11-22T14:16:41.000Z","values":[9386]},{"timestamp":"2023-11-22T14:16:42.000Z","values":[128]},{"timestamp":"2023-11-22T14:16:43.000Z","value'
||'s":[10841]},{"timestamp":"2023-11-22T14:16:44.000Z","values":[2057]},{"timestamp":"2023-11-22T14:16:45.000Z","values":[8660]},{"timestamp":"2023-11-22T14:16:46.000Z","values":[233]},{"timestamp":"2023-11-22T14:16:47.000Z","values":[315]},{"timestamp"'
||':"2023-11-22T14:16:48.000Z","values":[2348]}]',
'',
'------ Gold below ---------------- ',
'    SELECT  JSON_ARRAYAGG(',
'                 JSON_OBJECT',
'                 (',
'                        ''timestamp'' VALUE TO_CHAR((  TX_TIMESTAMP  ), ''YYYY-MM-DD"T"HH24:MI:SS".000Z"'' ), ',
'                        ''values'' VALUE json_array(TOTAL_PAY)   ',
'                ) ORDER BY TX_TIMESTAMP   )  as TX_DATA  ',
'FROM FD_TX_HISTORIC_DATA  ;',
'*/',
'json_input_str varchar2(4000) := ''[',
'        {"timestamp":"2023-11-22T08:10:11.000Z","values":  8329  },',
'        {"timestamp":"2023-11-22T08:10:12.000Z","values":  9672  },',
'        {"timestamp":"2023-11-22T08:10:13.000Z","values":  8263  },',
'        {"timestamp":"2023-11-22T08:10:14.000Z","values":  105511  },',
'        {"timestamp":"2023-11-22T08:10:15.000Z","values":  6895  },',
'        {"timestamp":"2023-11-22T08:10:16.000Z","values":  1055649  },',
'        {"timestamp":"2023-11-22T08:10:17.000Z","values":  6895  },',
'        {"timestamp":"2023-11-22T08:10:18.000Z","values":  8329  },',
'        {"timestamp":"2023-11-22T08:10:19.000Z","values":  9672  },',
'        {"timestamp":"2023-11-22T08:10:20.000Z","values":  8263  },',
'        {"timestamp":"2023-11-22T08:10:21.000Z","values":  105511  },',
'        {"timestamp":"2023-11-22T08:10:22.000Z","values":  6895  },',
'        {"timestamp":"2023-11-22T08:10:23.000Z","values":  1055649  },',
'        {"timestamp":"2023-11-22T08:10:24.000Z","values":  6895  }',
']'';',
'',
'',
'BEGIN ',
'',
'',
'',
'',
' --Htp.p(v_TX_TIMESTAMP);',
' /*',
' delete from FD_TX_HISTORIC_DATA;',
'',
' FOR Lcntr IN 1..14 LOOP',
'         FD_TX_HISTORICDATA_INSERTS (v_time_diff);',
'        v_time_diff := v_time_diff + 1;',
' END LOOP;',
'*/',
' ',
'    Htp.p(''Ideal Case          -------------------------------<br/><pre>''||json_input_str);  ',
'',
'',
'   Htp.p(''</pre></br/>---------------------------->>>"2023-11-14T18:54:11.000Z", </br/>  '');',
'   Htp.p(''</br/>---------------------------->>>"2023-11-14T18:54:12.000Z", </br/>  '');',
'   For row_1 In C1 Loop  ',
'       Htp.p(''</br/>---------------------------->>>''||TO_CHAR(( row_1.TX_TIMESTAMP  ), ''YYYY-MM-DD"T"HH24:MI:SS".000Z"'' )  ||'' ------------------> $''||row_1.TOTAL_PAY);',
'    End Loop;',
'    ',
'',
'END;'))
,p_plug_source_type=>'NATIVE_PLSQL'
,p_plug_display_condition_type=>'NEVER'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93356690251019656)
,p_plug_name=>'Spinner'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(62183755337085053)
,p_plug_display_sequence=>20
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'',
'begin ',
'null;',
'end;',
''))
,p_plug_source_type=>'NATIVE_PLSQL'
,p_plug_display_condition_type=>'NEVER'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(93356861126019658)
,p_plug_name=>'Timer'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(62183755337085053)
,p_plug_display_sequence=>10
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'',
'begin ',
'        Htp.p(''Hello there ......... '');',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
);
wwv_flow_imp.component_end;
end;
/
