select  ID  from BANK_CUSTOMERS where upper(email) = upper(v('APP_USER'));
------------------
  CREATE TABLE "CC_FD" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CUST_ID" NUMBER, 
	"CC_NO" NUMBER, 
	"STATUS" VARCHAR2(50), 
	"VALIDITY" DATE, 
	"FIRST_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(50), 
	"BANK_NAME" VARCHAR2(50), 
	"COMMENTS" VARCHAR2(100), 
	"CARD_TYPE" VARCHAR2(10), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
------------
DECLARE 
  card_number VARCHAR2(100) := ''; 
  card_number_begin number := '1'; 
  i NUMBER := 1; 
  l_status varchar2(10) := 'OnHold';
BEGIN 
     
    card_number_begin :=  CASE 
                          WHEN round(dbms_random.value(1,2)) = 1 THEN '4' -- Visa starts with 4
                          WHEN round(dbms_random.value(1,2)) = 2 THEN '5' -- Mastercard starts with 2 or 5 
                    END;  
    if card_number_begin is null then
        card_number_begin := 2; -- Mastercard starts with 2 or 5
    end if;  
    
  -- Generate remaining digits 
    WHILE i < 16 LOOP  
        card_number :=  card_number ||  round(DBMS_Random.Value(0,9),0);    
        i := i + 1; 
    END LOOP;  
  
--   -- Add the check digit 
   card_number := card_number_begin || card_number; 
   
   insert into CC_FD (CUST_ID, FIRST_NAME, CC_NO, STATUS ) values (:cust_id, :customer_name, card_number, l_status );
    
   commit;

END; 
-----------------------
declare

l_cust_id number := TO_NUMBER(:P95_CUST_ID) ;
l_card_no number := TO_NUMBER(:P95_CUST_ID) ;
 
begin
 

update cc_fd set Status = 'Active',  CARD_TYPE = :P95_CARD_TYPE where CUST_ID =  l_cust_id returning CC_NO into l_card_no  ;

l_card_no := SUBSTR(l_card_no, -4);
 
 :P95_STATUS := 'Congratulations, Your Card ending with number '||l_card_no||' has been Auto Approved !. PIN will be last 4 digits of your card number';

end;