    ```sql 
        <copy>
        CREATE TABLE "CC_FD" 
        (	
            "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 99999999
            INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
            "CUST_ID" NUMBER, 
        ) ;
        </copy>
    ``` 
    ----

    ```sql 
        <copy>
        BEGIN 
            -- Call function to generate random transactions between date range
            -- Page numbers and Page item names will vary as per your setup
            FD_BANK_TXS_INSERTS(  :P85_START , :P85_END);
        END;
        </copy>
    ``` 

