prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/app_114_push_notifications_credentials.sql
@@workspace/credentials/credentials_for_mycohereai3.sql
@@workspace/remote_servers/wkrfs4xeqva1jcu_ind23aiv2_adb_us_phoenix_1_oraclecloudapps_com_ords_docuserws.sql
@@workspace/remote_servers/mycohereai3.sql
@@application/shared_components/data_profiles/issuecard.sql
@@application/shared_components/data_profiles/ccinvoke.sql
@@application/shared_components/web_sources/issuecard.sql
@@application/shared_components/web_sources/ccinvoke.sql
@@application/shared_components/workflow/task_definitions/new_customer_onboarding_task.sql
@@application/shared_components/workflow/workflows/new_customer_workflow.sql
@@application/shared_components/workflow/workflows/mybankwf1.sql
@@application/shared_components/navigation/lists/finserv_nav_home.sql
@@application/shared_components/navigation/lists/customers_nav.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/application_configuration.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/navigation/lists/user_settings.sql
@@application/shared_components/navigation/lists/finserv_nav.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_graph24_png.sql
@@application/shared_components/files/icons_graph256_png.sql
@@application/shared_components/files/icons_graph64_png.sql
@@application/shared_components/files/icons_graph32_png.sql
@@application/shared_components/files/icons_maps32_png.sql
@@application/shared_components/files/icons_json_png.sql
@@application/shared_components/files/icons_detect_png.sql
@@application/shared_components/files/icons_data_png.sql
@@application/shared_components/files/icons_datasearch_png.sql
@@application/shared_components/files/icons_messaging_png.sql
@@application/shared_components/files/icons_chat_png.sql
@@application/shared_components/files/icons_scheduler_png.sql
@@application/shared_components/files/icons_vector_png.sql
@@application/shared_components/files/icons_speech_png.sql
@@application/shared_components/files/icons_genai_png.sql
@@application/shared_components/files/icons_process_png.sql
@@application/shared_components/files/icons_blockchain_png.sql
@@application/shared_components/files/icons_transactions_png.sql
@@application/shared_components/files/icons_chatbot_png.sql
@@application/shared_components/files/images_json118_png.sql
@@application/shared_components/files/icons_json56_png.sql
@@application/shared_components/files/icons_json24_png.sql
@@application/shared_components/files/icons_speech24_png.sql
@@application/shared_components/files/icons_chatbot32_png.sql
@@application/shared_components/files/icons_blockchain32_png.sql
@@application/shared_components/files/icons_transactionmanagement32_png.sql
@@application/shared_components/files/icons_vectors32_png.sql
@@application/shared_components/files/icons_datagen32_png.sql
@@application/shared_components/files/icons_workflow32_png.sql
@@application/shared_components/files/icons_process32_png.sql
@@application/shared_components/files/apex_data_pkg_aichat_295348_zip.sql
@@application/shared_components/files/apex_data_pkg_appusers_154405_zip.sql
@@application/shared_components/files/apex_data_pkg_appusers_old_285274_zip.sql
@@application/shared_components/files/apex_data_pkg_audio_t_542850_zip.sql
@@application/shared_components/files/apex_data_pkg_bank_accounts_155475_zip.sql
@@application/shared_components/files/apex_data_pkg_bank_customers_240998_zip.sql
@@application/shared_components/files/apex_data_pkg_bank_customers_beneficia_415285_zip.sql
@@application/shared_components/files/apex_data_pkg_bank_transfers_89118_zip.sql
@@application/shared_components/files/apex_data_pkg_cc_fd_416360_zip.sql
@@application/shared_components/files/apex_data_pkg_cc_fd_secure_193520_zip.sql
@@application/shared_components/files/apex_data_pkg_cndemo_document_ai_docs_356878_zip.sql
@@application/shared_components/files/apex_data_pkg_common_role_550443_zip.sql
@@application/shared_components/files/apex_data_pkg_common_users_20024_zip.sql
@@application/shared_components/files/apex_data_pkg_customers_408445_zip.sql
@@application/shared_components/files/apex_data_pkg_dept_209411_zip.sql
@@application/shared_components/files/apex_data_pkg_devrel_main_762678_zip.sql
@@application/shared_components/files/apex_data_pkg_devrel_monthlymetrics_553934_zip.sql
@@application/shared_components/files/apex_data_pkg_emp_679256_zip.sql
@@application/shared_components/files/apex_data_pkg_fd_anm_633769_zip.sql
@@application/shared_components/files/apex_data_pkg_fd_bank_names_579875_zip.sql
@@application/shared_components/files/apex_data_pkg_fd_bank_transactions_917126_zip.sql
@@application/shared_components/files/apex_data_pkg_fd_business_rules_78700_zip.sql
@@application/shared_components/files/apex_data_pkg_fd_transactions_log_761291_zip.sql
@@application/shared_components/files/apex_data_pkg_fd_tx_historic_data_446441_zip.sql
@@application/shared_components/files/apex_data_pkg_finbank_accounts_616597_zip.sql
@@application/shared_components/files/apex_data_pkg_fundstransfer_queue_tabl_983177_zip.sql
@@application/shared_components/files/apex_data_pkg_hlterm_899199_zip.sql
@@application/shared_components/files/apex_data_pkg_js_procedures_117090_zip.sql
@@application/shared_components/files/apex_data_pkg_machine_learning_configs_864043_zip.sql
@@application/shared_components/files/apex_data_pkg_myaudiodata_891592_zip.sql
@@application/shared_components/files/apex_data_pkg_my_books_75981_zip.sql
@@application/shared_components/files/apex_data_pkg_pizzashops_333685_zip.sql
@@application/shared_components/files/apex_data_pkg_pizza_delivery_mode_929426_zip.sql
@@application/shared_components/files/apex_data_pkg_pizza_order_132001_zip.sql
@@application/shared_components/files/apex_data_pkg_pizza_order_details_83104_zip.sql
@@application/shared_components/files/apex_data_pkg_related_labels_315113_zip.sql
@@application/shared_components/files/apex_data_pkg_retail_shopping_636951_zip.sql
@@application/shared_components/files/apex_data_pkg_retail_shopping_fd_73523_zip.sql
@@application/shared_components/files/apex_data_pkg_shops_659222_zip.sql
@@application/shared_components/files/apex_data_pkg_shop_items_493938_zip.sql
@@application/shared_components/files/apex_data_pkg_technologies_569311_zip.sql
@@application/shared_components/files/apex_data_pkg_unesco_sites_303523_zip.sql
@@application/shared_components/files/apex_data_pkg_user_profile_bc_328083_zip.sql
@@application/shared_components/files/apex_data_pkg_us_hospitals_936822_zip.sql
@@application/shared_components/files/apex_data_pkg_vector_store_166934_zip.sql
@@application/shared_components/files/icons_usd_png.sql
@@application/shared_components/files/atm_atm_png.sql
@@application/shared_components/files/atm_atm2_png.sql
@@application/shared_components/files/atm_atm3_png.sql
@@application/shared_components/files/atm_money_gif.sql
@@application/shared_components/files/atm_trash_gif.sql
@@application/shared_components/files/audio_beep1_mp3.sql
@@application/shared_components/files/audio_collectcash_mp3.sql
@@application/shared_components/files/audio_contactsupport_mp3.sql
@@application/shared_components/files/audio_enterpin_mp3.sql
@@application/shared_components/files/audio_invalidpin_mp3.sql
@@application/shared_components/files/audio_enteramount_mp3.sql
@@application/shared_components/files/audio_lessthan5k_mp3.sql
@@application/shared_components/files/retailimages_delivery_biker1_jpeg.sql
@@application/shared_components/files/retailimages_delivery_biker2_jpeg.sql
@@application/shared_components/files/retailimages_delivery_biker3_jpeg.sql
@@application/shared_components/files/retailimages_delivery_carry1_jpeg.sql
@@application/shared_components/files/retailimages_delivery_carry2_jpeg.sql
@@application/shared_components/files/retailimages_delivery_carry3_jpeg.sql
@@application/shared_components/files/retailimages_delivery_carry4_jpeg.sql
@@application/shared_components/files/retailimages_delivery_inventory_jpeg.sql
@@application/shared_components/files/retailimages_delivery_marketing_jpeg.sql
@@application/shared_components/files/retailimages_delivery_orders_jpeg.sql
@@application/shared_components/files/retailimages_delivery_truck5_jpeg.sql
@@application/shared_components/files/retailimages_delivery_truck6_jpeg.sql
@@application/shared_components/files/retailimages_delivery_truck8_jpeg.sql
@@application/shared_components/files/retailimages_delivery_trucker1_jpeg.sql
@@application/shared_components/files/retailimages_delivery_trucker2_jpeg.sql
@@application/shared_components/files/retailimages_delivery_trucker3_jpeg.sql
@@application/shared_components/files/retailimages_delivery_waiter1_jpeg.sql
@@application/shared_components/files/retailimages_delivery_waiter2_jpeg.sql
@@application/shared_components/files/retailimages_delivery_waiter3_jpeg.sql
@@application/shared_components/files/retailimages_delivery_waiter4_jpeg.sql
@@application/shared_components/files/retailimages_delivery_waiter5_jpeg.sql
@@application/shared_components/files/retailimages_delivery_waiter6_jpeg.sql
@@application/shared_components/files/retailimages_delivery_waiter7_jpeg.sql
@@application/shared_components/files/retailimages_delivery_warehouse_jpeg.sql
@@application/shared_components/files/retailimages_files_images_layers_2x_png.sql
@@application/shared_components/files/retailimages_files_images_layers_png.sql
@@application/shared_components/files/retailimages_files_images_marker_icon_2x_png.sql
@@application/shared_components/files/retailimages_files_images_marker_icon_png.sql
@@application/shared_components/files/retailimages_files_images_marker_shadow_png.sql
@@application/shared_components/files/retailimages_files_leaflet_routing_machine_css.sql
@@application/shared_components/files/retailimages_files_leaflet_routing_machine_js.sql
@@application/shared_components/files/retailimages_files_leaflet_css.sql
@@application/shared_components/files/retailimages_files_leaflet_js.sql
@@application/shared_components/files/retailimages_files_shopimg_jpeg.sql
@@application/shared_components/files/retailimages_icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/retailimages_icons_app_icon_192_png.sql
@@application/shared_components/files/retailimages_icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/retailimages_icons_app_icon_32_png.sql
@@application/shared_components/files/retailimages_icons_app_icon_512_png.sql
@@application/shared_components/files/retailimages_icons_bike2_png.sql
@@application/shared_components/files/retailimages_icons_bike3_png.sql
@@application/shared_components/files/retailimages_icons_bike_f_png.sql
@@application/shared_components/files/retailimages_icons_bike_r_png.sql
@@application/shared_components/files/retailimages_icons_truck1_png.sql
@@application/shared_components/files/retailimages_icons_truck1_f_png.sql
@@application/shared_components/files/retailimages_icons_truck1_r_png.sql
@@application/shared_components/files/retailimages_icons_truck2_png.sql
@@application/shared_components/files/retailimages_pizzanames_beanburger1_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_biancapizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_cheesechickenburger_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_cheesepizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_cheezeburger_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_chickenburger1_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_chickenburger2_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_chickenburger3_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_chickenpizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_chillipizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_cornpizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_dietcoke_png.sql
@@application/shared_components/files/retailimages_pizzanames_margheritapizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_mushroompizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_orange_png.sql
@@application/shared_components/files/retailimages_pizzanames_paneerburger_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_paneerburger1_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_paneerburger2_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_paneerburger3_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_paneerburger4_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_paneerpizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_pepperonipizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_portobellomushroomburger_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_regularcoke_png.sql
@@application/shared_components/files/retailimages_pizzanames_salamipizza_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_salmonburger1_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_salmonburger2_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_salmonburger3_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_salmonburger4_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_sprite_png.sql
@@application/shared_components/files/retailimages_pizzanames_sundae1_png.sql
@@application/shared_components/files/retailimages_pizzanames_sundae2_png.sql
@@application/shared_components/files/retailimages_pizzanames_sundae3_png.sql
@@application/shared_components/files/retailimages_pizzanames_sundae4_png.sql
@@application/shared_components/files/retailimages_pizzanames_sundae5_png.sql
@@application/shared_components/files/retailimages_pizzanames_sundae6_png.sql
@@application/shared_components/files/retailimages_pizzanames_vegburger1_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_vegburger2_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_vegcheeseburger_jpeg.sql
@@application/shared_components/files/retailimages_pizzanames_veggiepizza_jpeg.sql
@@application/shared_components/files/retailimages_taxi_png.sql
@@application/shared_components/files/atm_cardmachine1_png.sql
@@application/shared_components/files/atm_cardmachine2_png.sql
@@application/shared_components/files/retailimages_files_images_pizza_gif.sql
@@application/shared_components/files/retailimages_files_images_pizza2_gif.sql
@@application/shared_components/files/retailimages_files_images_pizza5_gif.sql
@@application/shared_components/files/audio_cardhasbeenblocked_mp3.sql
@@application/shared_components/files/audio_download_mp3.sql
@@application/shared_components/files/audio_cardpin_mp3.sql
@@application/shared_components/files/audio_paymentdeclined_mp3.sql
@@application/shared_components/files/audio_paymentpendingcontactsupport_mp3.sql
@@application/shared_components/files/icons_payfail_gif.sql
@@application/shared_components/files/audio_chequedeposited_mp3.sql
@@application/shared_components/files/audio_chqdepositedthankyou_mp3.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_favicon_ico.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_bg_masthead_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_fullsize_1_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_fullsize_2_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_fullsize_3_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_fullsize_4_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_fullsize_5_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_fullsize_6_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_thumbnails_1_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_thumbnails_2_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_thumbnails_3_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_thumbnails_4_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_thumbnails_5_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_assets_img_portfolio_thumbnails_6_jpg.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_css_styles_css.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_index_html.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_js_scripts_js.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_favicon_ico.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_about_1_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_about_2_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_about_3_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_about_4_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_close_icon_svg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_header_bg_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_logos_facebook_svg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_logos_google_svg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_logos_ibm_svg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_logos_microsoft_svg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_map_image_png.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_navbar_logo_svg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_1_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_2_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_3_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_4_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_5_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_6_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_team_1_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_team_2_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_team_3_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_css_styles_css.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_index_html.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_js_scripts_js.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_finservbuilding_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_1a_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_2a_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_4a_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_3a_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_5a_jpg.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_assets_img_portfolio_6a_jpg.sql
@@application/shared_components/files/oda24_scripts_helper_js.sql
@@application/shared_components/files/oda24_scripts_settings_js.sql
@@application/shared_components/files/oda24_scripts_web_sdk_js.sql
@@application/shared_components/files/oda24_scripts_web_sdk_min_js.sql
@@application/shared_components/files/oda24_style_style_css.sql
@@application/shared_components/files/oda24_style_styles_css.sql
@@application/shared_components/files/oda_settings_min_js.sql
@@application/shared_components/files/templates_startbootstrap_creative_gh_pages_css_styles_min_css.sql
@@application/shared_components/files/templates_startbootstrap_agency_gh_pages_css_styles_min_css.sql
@@application/shared_components/files/atm_cardmachine3_png.sql
@@application/shared_components/files/images_slide6_png.sql
@@application/shared_components/files/images_slide5_png.sql
@@application/shared_components/files/images_slide4_png.sql
@@application/shared_components/files/images_slide3_png.sql
@@application/shared_components/files/images_slide2_png.sql
@@application/shared_components/files/images_slide1_png.sql
@@application/shared_components/files/icons_administration_png.sql
@@application/shared_components/files/icons_aisearch_png.sql
@@application/shared_components/files/icons_anomalydetection_png.sql
@@application/shared_components/files/icons_architecturepresentation_png.sql
@@application/shared_components/files/icons_bankers_png.sql
@@application/shared_components/files/icons_customeranalysis_png.sql
@@application/shared_components/files/icons_frauddetection_png.sql
@@application/shared_components/files/icons_home_png.sql
@@application/shared_components/files/icons_moneylaundering_png.sql
@@application/shared_components/files/icons_moneymules_png.sql
@@application/shared_components/files/icons_mytasks_png.sql
@@application/shared_components/files/icons_workflowconsle_png.sql
@@application/shared_components/files/images_nav_css.sql
@@application/shared_components/files/images_nav_min_css.sql
@@application/shared_components/files/icons_atmcash_png.sql
@@application/shared_components/files/oda_redwood_base_madhu_min_css.sql
@@application/shared_components/files/icons_fdpayment_png.sql
@@application/shared_components/files/icons_moneylaundering24_png.sql
@@application/shared_components/files/icons_moneymules24_png.sql
@@application/shared_components/files/icons_aisearch24_png.sql
@@application/shared_components/files/icons_customeranalysis24_png.sql
@@application/shared_components/files/icons_drauddetection24_png.sql
@@application/shared_components/files/icons_anomalydetection24_png.sql
@@application/shared_components/files/icons_frauddetection24_png.sql
@@application/shared_components/files/icons_checkdeposit24_png.sql
@@application/shared_components/files/icons_cashwithdrawal24_png.sql
@@application/shared_components/files/icons_bankers24_png.sql
@@application/shared_components/files/icons_atm24_png.sql
@@application/shared_components/files/icons_mytasks24_png.sql
@@application/shared_components/files/icons_workflow24_png.sql
@@application/shared_components/files/icons_transaction24_png.sql
@@application/shared_components/files/icons_reference24_png.sql
@@application/shared_components/files/icons_administration24_png.sql
@@application/shared_components/files/icons_home24_png.sql
@@application/shared_components/files/icons_customersearch24_png.sql
@@application/shared_components/files/icons_transactionsearch24_png.sql
@@application/shared_components/files/images_bankerhome_png.sql
@@application/shared_components/files/images_customerhome_png.sql
@@application/shared_components/files/images_developerhome_png.sql
@@application/shared_components/files/icons_applicationhistory_png.sql
@@application/shared_components/files/icons_applyforcard_png.sql
@@application/shared_components/files/icons_bankaccount_png.sql
@@application/shared_components/files/icons_bankcustomers_png.sql
@@application/shared_components/files/icons_bankstatement_png.sql
@@application/shared_components/files/icons_cart_png.sql
@@application/shared_components/files/icons_fundtransfer_png.sql
@@application/shared_components/files/icons_loanemi_png.sql
@@application/shared_components/files/icons_shopping_png.sql
@@application/shared_components/files/icons_updateprofile_png.sql
@@application/shared_components/files/icons_cashwithdrawal_png.sql
@@application/shared_components/files/icons_atm_png.sql
@@application/shared_components/files/icons_chequedeposit_png.sql
@@application/shared_components/files/icons_makepayment24_png.sql
@@application/shared_components/files/images_ind1600_jpg.sql
@@application/shared_components/files/images_ind4600_jpg.sql
@@application/shared_components/files/images_ind2600_jpg.sql
@@application/shared_components/files/images_ind5600_jpg.sql
@@application/shared_components/files/images_ind3600_jpg.sql
@@application/shared_components/files/images_ind7600_jpg.sql
@@application/shared_components/files/images_ind6600_jpg.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/app_icon_512_png.sql
@@application/shared_components/files/oda_web_sdk_js.sql
@@application/shared_components/files/oda_web_sdk_min_js.sql
@@application/shared_components/files/oda_settings_js.sql
@@application/shared_components/files/oda_redwood_base_madhu_css.sql
@@application/shared_components/files/ml_png.sql
@@application/shared_components/files/mml_png.sql
@@application/shared_components/files/rtg_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/app_access_control/bank_officer_role.sql
@@application/shared_components/security/app_access_control/bank_customer_role.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/sendnotification1.sql
@@application/shared_components/logic/application_processes/render_document.sql
@@application/shared_components/logic/application_processes/render_image.sql
@@application/shared_components/logic/application_processes/sendpushnotification.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_due.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_initiated.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_priority.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_state.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_type.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/shared_components/user_interface/lovs/workflow_charts_lov_time_unit.sql
@@application/shared_components/user_interface/lovs/workflow_console_lov_initiated.sql
@@application/shared_components/user_interface/lovs/workflow_console_lov_workflow_state.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/demo_purposes_only_custom_auth_scheme.sql
@@application/shared_components/security/authentications/custom_auth.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/plugins/region_type/cool_dashboard_v_2_0.sql
@@application/shared_components/plugins/template_component/theme_42_avatar.sql
@@application/shared_components/plugins/template_component/theme_42_badge.sql
@@application/shared_components/plugins/template_component/theme_42_button.sql
@@application/shared_components/plugins/template_component/theme_42_comments.sql
@@application/shared_components/plugins/template_component/theme_42_content_row.sql
@@application/shared_components/plugins/template_component/theme_42_media_list.sql
@@application/shared_components/plugins/template_component/theme_42_timeline.sql
@@application/shared_components/plugins/region_type/graphviz.sql
@@application/shared_components/data_loads/fd_ddl.sql
@@application/shared_components/data_loads/fd_ddl2.sql
@@application/shared_components/data_loads/fdd4.sql
@@application/shared_components/data_loads/test_ddl.sql
@@application/shared_components/data_loads/ddl6.sql
@@application/shared_components/data_loads/1.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00090.sql
@@application/pages/page_00091.sql
@@application/pages/page_00092.sql
@@application/pages/page_00093.sql
@@application/pages/page_00094.sql
@@application/pages/page_00095.sql
@@application/pages/page_00096.sql
@@application/pages/page_00097.sql
@@application/pages/page_00098.sql
@@application/pages/page_00099.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00103.sql
@@application/pages/page_00105.sql
@@application/pages/page_00111.sql
@@application/pages/page_00449.sql
@@application/pages/page_01111.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10020.sql
@@application/pages/page_10030.sql
@@application/pages/page_10031.sql
@@application/pages/page_10032.sql
@@application/pages/page_10033.sql
@@application/pages/page_10034.sql
@@application/pages/page_10035.sql
@@application/pages/page_10036.sql
@@application/pages/page_10040.sql
@@application/pages/page_10041.sql
@@application/pages/page_10042.sql
@@application/pages/page_10043.sql
@@application/pages/page_10044.sql
@@application/pages/page_10050.sql
@@application/pages/page_10051.sql
@@application/pages/page_10053.sql
@@application/pages/page_10054.sql
@@application/pages/page_10060.sql
@@application/pages/page_10061.sql
@@application/pages/page_20000.sql
@@application/pages/page_20010.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_12maytablestriggers_sql.sql
@@application/deployment/install/install_12mayfunctionspackgstriggersseqs_sql.sql
@@application/deployment/install/install_12maydatapkg_sql.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
